api_platform:
    title: Pyiurs Back Office
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        multipart: ['multipart/form-data']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    error_formats:
        jsonproblem: ['application/json']
    defaults:
        pagination_items_per_page: 50
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
        # state_options:
        #     processors:
        #         - App\State\UserPasswordHasher
    keep_legacy_inflector: false
    use_symfony_listeners: true
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header


